BEGIN;
CREATE TABLE IF NOT EXISTS usuarios (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS sesiones (
  token_hash TEXT PRIMARY KEY,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  expira TIMESTAMPTZ NOT NULL
);
ALTER TABLE mascotas ADD COLUMN IF NOT EXISTS usuario_id INTEGER REFERENCES usuarios(id);
CREATE INDEX IF NOT EXISTS mascotas_usuario_id_idx ON mascotas(usuario_id);
COMMIT;
