ALTER TABLE mascotas
  ADD COLUMN raza VARCHAR(150) NOT NULL DEFAULT '',
  ADD COLUMN pedigree BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN descripcion TEXT NOT NULL DEFAULT '',
  ADD COLUMN reporte TEXT NOT NULL DEFAULT '',
  ADD COLUMN fecha DATE;
